version: "3.3"

services:
    json-rpc-server:
        hostname: json-rpc-server
        container_name: json-rpc-server
        image: neznajki/docker-php73:latest
        volumes:
            - .:/www/default:cached
            - $HOME/.composer:$HOME/.composer:cached
            - $HOME/.ssh/:$HOME/.ssh:cached
            - /opt/phpstorm-coverage/:/opt/phpstorm-coverage/:cached
        ports:
            - 80
        dns:
            - 8.8.8.8
            - 10.252.252.252
        environment:
            - VIRTUAL_HOST=json-rpc-server.local
            - HTTPS_METHOD=noredirect
            - APACHE_DOCUMENT_ROOT=/www/default
            - HOME=$HOME

networks:
    default:
        external:
            name: local.net
