services:
    _defaults:
        autowire: true
        autoconfigure: true

    JsonRpcServerBundle\Subscriber\ExceptionSubscriber:
        class: JsonRpcServerBundle\Subscriber\ExceptionSubscriber
        arguments:
            - '@Psr\Log\LoggerInterface'
            - '%json_rpc_http_server.http_endpoint_path%'

    JsonRpcServerBundle\Subscriber\MethodExceptionEventSubscriber: ~

    JsonRpcServerBundle\Controller\ApiEndpointController: ~

    JsonRpcServerBundle\Service\MethodExecutorService: ~

    JsonRpcServerBundle\Service\MethodCollectionService: ~
